# Participation {#participation}

This is your research experience and it’s up to you to be the motivating force behind it. We expect lab members to be active participants in the science that we do in the lab, and in the larger scientific academic world. Discuss ideas. Make connections. Don’t get tunnel-vision but learn and read broadly. Question everything.

* Share your thoughts! Share your ideas! Share your expertise! We are a collaborative lab that wants to see everyone in the lab succeed. There should not be real or perceived competition among lab-mates. We do not “scoop” each other or take credit for other’s work. Part of the reason we love science and research is that it is fun to do and fun to work with other people.
* _Lab Meetings_ 
    + Grad students and postdocs will be expected to lead (at least) one lab meeting/quarter. You are always expected to participate in and contribute to discussions during lab meeting.
    + Do not be afraid to disagree in lab discussions but do it respectfully. We disagree with ideas, not necessarily with people. Keep the focus on the science, not the person.
* _Going to seminars_
    + Go to at least one per week (more in your first year as a grad student). Even if they seem slightly outside your wheelhouse, it is important to learn about what other fields are doing and you sometimes get great ideas!
* _Meeting with speakers_
    + Grad students and postdocs should be meeting with seminar speakers A LOT. If not every week, then probably every other week. Even if they don’t study something directly related to you. Get used to talking about your ideas with people and “thinking on your feet”. You never know when/how different connections might help you out!
* _Conferences_
    + Assuming the lab has money, each grad student and postdoc will be funded to attend at least one academic conference per year.
    + If an undergrad has taken a large role in a project and would like to attend, then this is also a possibility.
    + Conferences are fun, but don’t forget that they are professional too. You are expected to use your time wisely at the conference (see relevant talks, meet new people, etc). You’ll be expected to give a summary of the cool things you learned/saw at a conference after you return (if the entire lab did not attend).
    + If you want to attend other things (like workshops, or short-courses) just ask and we’ll see how well it fits and if we can find a way to get you there.
* _Social lab culture_
    + While not required, we encourage all lab members to participate in outside lab activities (quarterly lab dinners, lab lunches, etc, for example) to help build trust and camaraderie among lab-mates.    


