# General conduct in shared spaces {#conduct}

Every person in the lab has responsibility for maintaining a clean, productive and supportive environment in our shared spaces.

* Stay home if you’re not feeling well!
* Clean up after yourself – both in terms of kitchen/office spaces, and also in terms of experimental spaces.
* Be courteous – don’t have loud conversations in the office space, especially personal ones. Professional meetings (i.e. with a seminar speaker) are fine if that is the only space available, though it might be useful to look into reserving the department conference rooms for this is possible.
* Headphones indicate important work is happening so please respect other people’s desire to work uninterrupted.
* _Conflict Resolution_
  + As with any group of >1 people, misunderstandings, conflicts and annoyances will happen. If you are having difficulty interacting with another lab-mate, you are encouraged to find ways to communicate and resolve these problems on your own as adults with your lab-mates. As mentioned previously, we encourage clear and open communication.
  + Say something before it becomes a bigger problem.
  + Schedule a meeting with them to talk it out. Focus on listening to the other person to understand their perspective. Give folks the benefit of the doubt when possible. We don’t all need to be best friends with each other but we do all need to be courteous and professional colleagues.
  + Don’t gang up on people; don’t be ‘clique-y’
  + If it is something that cannot be resolved between the two of you, please let Kate know and we will work together to find a solution.
