# Time spent in the office/lab {#expectations}

We value “whole humans.” We know that science is just one part of your life. We value folks that find harmony between their work life and their non-work life. We don’t judge others based on whatever balance they find. We do not value workaholism.

* You are trusted to manage your time productively and efficiently. There is no official schedule of when you are expected to be in the lab (exceptions: fish duty), but there are benefits to folks being in the same area for spontaneous interactions, e.g. during core work hours (10ish to 3ish). Working from home is completely allowed but you should generally try to spend a majority of days in lab (when possible).
* Research assistants (e.g. undergrads) need to communicate with their direct supervisor (the grad student, postdoc or tech they are working with) about arranging their schedule. These schedules are more rigid as they are often made in consideration of experimental work. Research assistants are expected to arrive when agreed upon and give as much notice as possible if plans change.
* You do not need to tell Kate when you need to leave early or are taking a day off, just as you do not need to justify to lab-mates where you are. There are no gold stars given out for being the first one in or the last one out.
* Science is a creative process so try to ride the wave of productivity. Some days will be really good and productive; some days won’t. Sometimes you need a break and it’s okay to give yourself that. Sometimes you need to learn new habits to increase productivity. If you feel like you’re not making progress and you don’t know how to do so, or you’re having lots of bad days strung together, then talk to Kate to build a plan to form healthy productivity habits.
* Holidays
  + You don’t need to tell Kate when you’re taking a day off, you are trusted to manage your time responsibly.
  + But if you are going to be gone for more than a long weekend, it is your responsibility to make sure that the appropriate people know (Kate & other folks involved in your work) and that you arrange to have any duties you may have covered. Send Kate a Slack message to confirm that your time off does not interfere with any lab duties and then put the days that you will be away in the shared Google calendar. Tell Kate who will be covering for your responsibilities (if necessary).
  + In theory, holidays of any length are okay, but these should be made with consideration of your progress and any other responsibilities you may have. The longer the holiday, the more notice you should provide before you go.
