# Interactions with Kate {#interactions}

Your relationship with me is critical for your success and so making sure that we communicate effectively is important to me! I want you to feel like you know what your expectations are; if you ever feel unsure that you are meeting my expectations, or even what they are, please ask me. I value open, honest communication – I will always tell you if I think improvements need to be made with your progress and I will never view any questions or concerns you may have as frivolous or “stupid”. If something isn’t working or isn’t right, speak with me – it’s better to fix a problem when it’s small than when it snowballs into something big.

* I follow an open-door policy. If my office door is open then feel free to stop by and chat. If my door is closed, then I am either not around or am unavailable.
* I do not expect you to be constantly available via email/Slack. I expect you to find what work hours work best for you and stick to those (which may or may not line up with mine). I encourage you to work the number of hours that you need to be productive. Just for reference, I typically work 40 hours a week (sometimes less, rarely more).
* I generally do not check my work communications after normal work hours (MF ~8-6) so you are welcome to send me communication during those times, but just know that I likely will not respond until I am back in my normal work day (exception: you should call me immediately if something is going horribly wrong in the fish room!)
* Generally, graduate students and postdocs have a guaranteed weekly meeting with me; this can decrease (to every two weeks) as the trainee gains more independence. If you have a scheduled meeting with me, it is your responsibility to come prepared. This means updating your Powerpoint Log with the appropriate information for the meeting with me (this could include bullet points about topics we need to discuss, graphs of results to show me, etc). These updates should be made no later than the morning of your meeting with me.
* In addition to regular weekly meetings, I will meet with you once a year to go over your Individual Development Plan (IDP). This plan is designed to help you identify and prioritize training and professional development opportunities to help you best meet your long-term career goals.
* We will agree on deadlines for things together. It is your responsibility to get me things on time or let me know when things will be late and set a new (realistic) deadline
* It is my responsibility to get you feedback in a timely fashion. This will differ depending on what it is – some things I will try to get you back within a day or two (e.g. feedback on abstracts, emails, slack convos). Other things I will need longer (manuscript revisions) but I will always try to get feedback to you within two weeks as a general rule.
* Emergencies – contact me via my cell phone if/when emergencies arise (personal emergencies, or fish room related emergencies)
