# Fish care & experimental space {#fishcare}

Taking care of our fish colonies is one of our biggest responsibilities. Making sure the fish duties as performed as planned is critical because 1) our animals deserve to be as happy and healthy as possible, 2) keeping our stocks in good health is critical for our science and 3) we are bound by the rules of the Institutional Animal Care and Use Committee and everyone in the lab could face serious repercussions if our duties are not met.

* If you are taking care of fish, you are expected to attend fish training and read (and understand) the fish care manuals and SOPs (standard operating procedures).
* Everyone in the lab will be expected to share fish care and feeding duties. This will include weekends and some holidays. The fish must be checked EVERY SINGLE DAY. If you cannot make it in on your assigned day, it is your responsibility to contact the back-up person (and if that fails, contact Kate) and ensure that someone is there to check on them.
* If you see something wrong in the fish room – SAY SOMETHING. Nothing is “not your problem”.
* Never move experimental materials or delete data without express consent from the responsible person.
* Security – the door to the fish room needs to stay locked at all times. Check with Kate before bringing in any visitors to the fish room.
* Photos – taking photos of experimental set-ups is a good idea, but check with Kate before sharing them with anyone outside the lab.
